run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - revive
    - unused
    - gosimple
    - misspell
    - bodyclose
    - noctx
    - unconvert
    - prealloc
    - gocritic
    - nilerr

linters-settings:
  gofmt:
    simplify: true
  
  govet:
    enable:
      - fieldalignment
      - shadow
  
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  revive:
    rules:
      - name: exported
        severity: warning
  
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0